name: Lint
on:
  push:
    branches:
      - master
    paths:
      - "**.py"
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install poetry
        run: python -m pip install --upgrade poetry wheel
      # TODO: add caching of Poetry.lock
      - name: Install dependencies
        run: poetry install --no-root --with dev
      - name: Run mypy
        run: poetry run mypy .
